### ISSUE TITLE
OpenAI check results get ignored

### ISSUE THREAD

**Issue by dsent** [umputun/tg-spam#139]
I'm seeing a consistent pattern of messages, classified as spam by OpenAI checker, not being flagged automatically.
After marking the message as spam manually, I see things like this:
```- stopword: ham, not found
- cas: ham, record not found
- similarity: ham, 0.00/0.50
- classifier: ham, probability of ham: 90.98%
- openai: spam, Message contains solicitation for adult content and services, often associated with spam, confidence: 95%
```
So, it should've been marked by the bot automatically, but it haven't.
I'm not sure how to debug this further.

**Comment by umputun** [comment]
what is your open-ai related configuration for tg-spam?

**Comment by umputun** [comment]
I have checked the code and don't really see how this is possible unless you run the system in dry or training mode. As long as the OpenAI check is invoked and spam is detected, it should treat the overall result as spam. There are [multiples tests](https://github.com/umputun/tg-spam/blob/main/lib/tgspam/detector_test.go#L367-L367) covering all the cases with OpenAI detection, and I can't see anything wrong here.

**Comment by dsent** [comment]
The system was in the training mode. Still, the spam messages should've been marked, right? Without actually banning the users who posted them.
The full config (`docker-compose.yml`) was:
```YAML
version: '3.8'

services:
  tg-spam:
    image: umputun/tg-spam:latest
    hostname: tg-spam
    restart: always
    container_name: tg-spam
    user: <redacted>
    environment:
      - TZ=Europe/Belgrade
      - TELEGRAM_TOKEN=<redacted>
      - TELEGRAM_GROUP=<redacted>
      - ADMIN_GROUP=<redacted>
      - LOGGER_ENABLED=true
      - LOGGER_FILE=/srv/log/tg-spam.log
      - LOGGER_MAX_SIZE=5M
      - FILES_DYNAMIC=/srv/var
      - NO_SPAM_REPLY=true
      - OPENAI_TOKEN=<redacted>
      - OPENAI_VETO=true
      - OPENAI_MODEL=gpt-4o
      - MAX_EMOJI=-1
      - MESSAGE_WARN=""
      - TRAINING=true
      - HISTORY_DURATION=24h
      - HISTORY_MIN_SIZE=5000
    volumes:
      - ./log:/srv/log
      - ./var:/srv/var
      - ./data:/srv/data
    command: --super=<redacted> --super=<redacted>
```
Now I changed it from training mode to production mode with softbans and OpenAI veto disabled (because of #138). Will probably see if it worked in a few hours when all the spam bots are back to work 😄
